"""empty message

Revision ID: 54a12b0063bb
Revises: 7b5341c2d6bc
Create Date: 2023-01-24 14:37:08.210904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54a12b0063bb'
down_revision = '7b5341c2d6bc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activities', sa.Column('type', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activities', 'type')
    # ### end Alembic commands ###
