"""empty message

Revision ID: 7b5341c2d6bc
Revises: 947e660e9b90
Create Date: 2023-01-21 13:21:01.692426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b5341c2d6bc'
down_revision = '947e660e9b90'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activities', sa.Column('name', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activities', 'name')
    # ### end Alembic commands ###
