"""empty message

Revision ID: 86fa24400d93
Revises: d17b68788e80
Create Date: 2023-01-19 12:56:14.253612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86fa24400d93'
down_revision = 'd17b68788e80'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
