"""empty message

Revision ID: 9057677959eb
Revises: 3983cf7d7c58
Create Date: 2023-01-20 16:51:18.258142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9057677959eb'
down_revision = '3983cf7d7c58'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('opinions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_approved', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('positive', 'negative', name='status'), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('plan', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_opinions_id'), 'opinions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_opinions_id'), table_name='opinions')
    op.drop_table('opinions')
    # ### end Alembic commands ###
