"""empty message

Revision ID: de56c2b41c5c
Revises: 60db3e457be0
Create Date: 2023-01-20 14:35:40.789920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de56c2b41c5c'
down_revision = '60db3e457be0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activities', sa.Column('type', sa.String(length=50), nullable=True))
    op.create_foreign_key(None, 'courses', 'activities', ['id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'courses', type_='foreignkey')
    op.drop_column('activities', 'type')
    # ### end Alembic commands ###
