"""empty message

Revision ID: efd41ed3f3ef
Revises: 9057677959eb
Create Date: 2023-01-20 17:01:57.433408

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'efd41ed3f3ef'
down_revision = '9057677959eb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('opinions', sa.Column('plan_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'opinions', 'plans', ['plan_id'], ['id'])
    op.drop_column('opinions', 'plan')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('opinions', sa.Column('plan', mysql.VARCHAR(length=50), nullable=False))
    op.drop_constraint(None, 'opinions', type_='foreignkey')
    op.drop_column('opinions', 'plan_id')
    # ### end Alembic commands ###
