"""empty message

Revision ID: f69773b1fa4e
Revises: 7b77ac08e57f
Create Date: 2023-01-03 11:25:25.530831

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f69773b1fa4e'
down_revision = '7b77ac08e57f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ects', sa.Integer(), nullable=False),
    sa.Column('cnps', sa.Integer(), nullable=False),
    sa.Column('zzu', sa.Integer(), nullable=False),
    sa.Column('bu', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activities_id'), 'activities', ['id'], unique=False)
    op.create_table('courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hours_count', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('type', sa.Enum('laboratory', 'practice', 'lecture', 'project', 'seminar', 'lang_course', 'thesis', name='type'), nullable=False),
    sa.Column('completing_form', sa.String(length=50), nullable=True),
    sa.Column('course_form', sa.Enum('stationary', 'remote', name='form'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_courses_id'), 'courses', ['id'], unique=False)
    op.create_table('modules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_modules_id'), 'modules', ['id'], unique=False)
    op.create_table('semesters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('max_ects_deficit', sa.Integer(), nullable=False),
    sa.Column('semester_number', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_semesters_id'), 'semesters', ['id'], unique=False)
    op.create_table('fields',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('profile', sa.Enum('academic', 'practical', name='profile'), nullable=False),
    sa.Column('level', sa.Enum('undergraduate', 'engineering', name='level'), nullable=False),
    sa.Column('faculty_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['faculty_id'], ['faculties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fields_id'), 'fields', ['id'], unique=False)
    op.create_table('plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('form', sa.Enum('fulltime', 'parttime', name='form'), nullable=True),
    sa.Column('number_of_semesters', sa.Integer(), nullable=True),
    sa.Column('lang', sa.String(length=100), nullable=True),
    sa.Column('field_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['field_id'], ['fields.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plans_id'), 'plans', ['id'], unique=False)
    op.create_table('plan_semester',
    sa.Column('semester_id', sa.Integer(), nullable=True),
    sa.Column('plan_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.ForeignKeyConstraint(['semester_id'], ['semesters.id'], )
    )
    op.drop_column('faculties', 'profile')
    op.drop_column('faculties', 'level')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('faculties', sa.Column('level', mysql.VARCHAR(collation='utf8_bin', length=50), nullable=False))
    op.add_column('faculties', sa.Column('profile', mysql.VARCHAR(collation='utf8_bin', length=50), nullable=False))
    op.drop_table('plan_semester')
    op.drop_index(op.f('ix_plans_id'), table_name='plans')
    op.drop_table('plans')
    op.drop_index(op.f('ix_fields_id'), table_name='fields')
    op.drop_table('fields')
    op.drop_index(op.f('ix_semesters_id'), table_name='semesters')
    op.drop_table('semesters')
    op.drop_index(op.f('ix_modules_id'), table_name='modules')
    op.drop_table('modules')
    op.drop_index(op.f('ix_courses_id'), table_name='courses')
    op.drop_table('courses')
    op.drop_index(op.f('ix_activities_id'), table_name='activities')
    op.drop_table('activities')
    # ### end Alembic commands ###
