"""empty message

Revision ID: fd8207b9224f
Revises: 67e9fb1723f9
Create Date: 2023-01-20 17:44:35.052187

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fd8207b9224f'
down_revision = '67e9fb1723f9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('semesters_ibfk_1', 'semesters', type_='foreignkey')
    op.drop_column('semesters', 'plan_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('semesters', sa.Column('plan_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.create_foreign_key('semesters_ibfk_1', 'semesters', 'plans', ['plan_id'], ['id'])
    # ### end Alembic commands ###
